def levenshtein(s1: str, s2: str, w_del: int, w_ins: int, w_sub: int
                ) -> int: ...
def fuzzy_match(query: str, against: list[str], amount: int
                ) -> tuple[int, int]: ...
def fuzzy_match_one(query: str, against: list[str]) -> tuple[int, int]: ...

